### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by ghost** [elixircnx/openmaize#89]
Hello,

I have tried just this morning to run the installer and I am running into an issue.

OS: Ubuntu 16.04
Elixir: Same results for 1.3.3, 1.4.0, 1.4.1
Erlang/OTP: 19

I'm using kiex to manage elixir versions.

When I try to run the installer after creating a new app, I get the following error:

```
$ mix archive.install https://github.com/riverrun/openmaize/raw/master/installer/archives/openmaize_phx.ez
Are you sure you want to install archive "https://github.com/riverrun/openmaize/raw/master/installer/archives/openmaize_phx.ez"? [Yn] 
* creating /home/m/.kiex/mix/archives/elixir-1.4.1/openmaize_phx
** (MatchError) no match of right hand side value: {:error, :bad_directory}
    (mix) lib/mix/tasks/archive.install.ex:97: Mix.Tasks.Archive.Install.install/3
    (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.do_install/3
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

**Comment by ghost** [comment]
When I use the version number, the command seems to work as intended.

```
mix archive.install https://github.com/riverrun/openmaize/raw/master/installer/archives/openmaize_phx-2.8.0.ez
```

**Comment by riverrun** [comment]
Thanks for pointing that out.
